# Generated by Django 5.1.3 on 2024-11-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyect',
            old_name='technology',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proyect',
            old_name='title',
            new_name='rut',
        ),
        migrations.RemoveField(
            model_name='proyect',
            name='description',
        ),
        migrations.AddField(
            model_name='proyect',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
